title: Zhengyang's Homepage
page-top-title: Zhengyang Bi(William)
top-section-bg-text: My major is mechanical engineering. I am insterested in robotic control.
home-subtitle: 
copyright-text: '&copy; ZhengyangBi 2023-2026. All Rights Reserved.'
